# Generated by Django 4.2 on 2023-05-12 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='perfil',
            field=models.ForeignKey(default='Tus muertos', on_delete=django.db.models.deletion.CASCADE, to='core.profile'),
        ),
    ]
