# Generated by Django 4.2 on 2023-05-12 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_post_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='perfil',
        ),
    ]
