# Generated by Django 4.2 on 2023-05-12 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_post_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
