# Generated by Django 4.2 on 2023-05-31 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_followerscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='background',
            field=models.ImageField(default='timeline-1.jpg', upload_to='background_images'),
        ),
    ]
