# Generated by Django 4.2 on 2023-06-01 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AddField(
            model_name='comment',
            name='post_id',
            field=models.CharField(default='265105a0-4c75-469e-af66-cc57d2ce2388', max_length=500),
            preserve_default=False,
        ),
    ]
